=== shadih/mygittestproject/IpagPreprocess/src/main/resources/valuepack/conf/PreProcessXmlConfig.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns="http://config.pd.vp.expert.uca.hp.com/"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.0"
	targetNamespace="http://config.pd.vp.expert.uca.hp.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

  <xs:element name="PreProcessPolicies">  
    <xs:complexType>
      <xs:sequence>
        <xs:element name="passThru">  
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:boolean" name="enablePublish"/>
              <xs:element name="eventNames">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="eventName" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
     <xs:element name="fileTargets">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="fileTarget" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:boolean" name="enableLogging"/>
                    <xs:element type="xs:string" name="fileName"/>
                    <xs:element name="eventNames">
                      <xs:complexType>
                        <xs:sequence>
                   			<xs:element type="xs:string" name="eventName" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element> 
     <xs:element name="cascadeTargets">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cascadeTarget" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:boolean" name="enableCascading"/>
                    <xs:element type="xs:string" name="vpName"/>
                    <xs:element type="xs:string" name="scenarioName"/>
                    <xs:element type="xs:float" name="version"/> 
                    <xs:element name="eventNames">
                      <xs:complexType> 
                        <xs:sequence> 
                          <xs:element type="xs:string" name="eventName" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name" use="required"/>
                </xs:complexType>
                <xs:unique name="unique-name">
			      <xs:selector xpath="cascadeTarget"/>    
			      <xs:field xpath="@name"/>          
			   </xs:unique>  
              </xs:element>   
            </xs:sequence>
          </xs:complexType>
        </xs:element>    
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== shadih/mygittestproject/IpagPreprocess/target/vp-build-dir/vp/deploy/ipagPreprocess-0.12/conf/PreProcessXmlConfig.SAREA.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PreProcessPolicies xmlns="http://config.pd.vp.expert.uca.hp.com/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="PreProcessXmlConfig.xsd">
	<passThru>
		<enablePublish>true</enablePublish>
		<eventNames>
			<eventName>50002/100/15</eventName>
			<eventName>50002/100/47</eventName>
			<eventName>50002/100/48</eventName>
			<eventName>50002/100/49</eventName>
			<eventName>50002/100/50</eventName>
			<eventName>50002/100/59</eventName>
			<eventName>50002/100/3</eventName>
			<eventName>50002/100/4</eventName>
			<eventName>50002/100/5</eventName>
			<eventName>50002/100/6</eventName>
			<eventName>50002/100/7</eventName>
			<eventName>50002/100/8</eventName>
			<eventName>50002/100/9</eventName>
			<eventName>50002/100/10</eventName>
			<eventName>50002/100/11</eventName>
			<eventName>50002/100/12</eventName>
			<eventName>50002/100/13</eventName>
			<eventName>50002/100/14</eventName>
			<eventName>50002/100/17</eventName>
			<eventName>50002/100/18</eventName>
			<eventName>50002/100/19</eventName>
			<eventName>50002/100/21</eventName>
			<eventName>50002/100/22</eventName>
			<eventName>50002/100/23</eventName>
			<eventName>50002/100/24</eventName>
			<eventName>50002/100/25</eventName>
			<eventName>50002/100/26</eventName>
			<eventName>50002/100/27</eventName>
			<eventName>50002/100/28</eventName>
			<eventName>50002/100/29</eventName>
			<eventName>50002/100/30</eventName>
			<eventName>50002/100/31</eventName>
			<eventName>50002/100/32</eventName>
			<eventName>50002/100/33</eventName>
			<eventName>50002/100/34</eventName>
			<eventName>50002/100/35</eventName>
			<eventName>50002/100/36</eventName>
			<eventName>50002/100/37</eventName>
			<eventName>50002/100/38</eventName>
			<eventName>50002/100/39</eventName>
			<eventName>50002/100/40</eventName>
			<eventName>50002/100/41</eventName>
			<eventName>50002/100/42</eventName>
			<eventName>50002/100/43</eventName>
			<eventName>50002/100/44</eventName>
			<eventName>50002/100/45</eventName>
			<eventName>50002/100/46</eventName>
			<eventName>50002/100/52</eventName>
			<eventName>50002/100/53</eventName>
			<eventName>50002/100/54</eventName>
			<eventName>50002/100/55</eventName>
			<eventName>50002/100/56</eventName>
			<eventName>50002/100/57</eventName>
			<eventName>50002/100/58</eventName>
			<eventName>50002/100/60</eventName>
			<eventName>50002/100/61</eventName>
			<eventName>50002/100/62</eventName>
			<eventName>50002/100/63</eventName>
			<eventName>50002/100/64</eventName>
			<eventName>50002/100/65</eventName>
			<eventName>50002/100/66</eventName>
			<eventName>50002/100/67</eventName>
			<eventName>50002/100/68</eventName>
			<eventName>50002/100/69</eventName>
			<eventName>50002/100/70</eventName>
			<eventName>50002/100/71</eventName>
			<eventName>50002/100/72</eventName>
			<eventName>50003/100/26</eventName>
			<eventName>50003/100/27</eventName>
			<eventName>50003/100/1</eventName>
			<eventName>50003/100/28</eventName>
			<eventName>50007/100/6</eventName>
			<eventName>50007/100/8</eventName>
			<eventName>50007/100/9</eventName>
			<eventName>50004/1/40</eventName>
			<eventName>50004/1/41</eventName>
			<eventName>50004/1/42</eventName>
			<eventName>50004/1/43</eventName>
			<eventName>50004/1/44</eventName>
			<eventName>50004/1/45</eventName>
			<eventName>50004/1/46</eventName>
			<eventName>50004/1/47</eventName>
			<eventName>50004/1/48</eventName>
			<eventName>50004/1/49</eventName>
			<eventName>50004/1/50</eventName>
			<eventName>50004/1/51</eventName>
			<eventName>50004/1/52</eventName>
			<eventName>50004/2/2</eventName>
			<eventName>50007/2/1</eventName>
			<eventName>50004/1/2</eventName>
			<eventName>50004/2/8</eventName>
			<eventName>50006/100/1</eventName>
			<eventName>50006/100/2</eventName>
			<eventName>50006/100/3</eventName>
			<eventName>50006/100/4</eventName>
			<eventName>50006/100/5</eventName>
			<eventName>50006/100/6</eventName>
			<eventName>50006/100/7</eventName>
			<eventName>50006/100/8</eventName>
			<eventName>50006/100/9</eventName>
			<eventName>50006/100/10</eventName>
			<eventName>50006/100/11</eventName>
			<eventName>50006/100/12</eventName>
			<eventName>50006/100/13</eventName>
			<eventName>50006/100/14</eventName>
			<eventName>50006/100/15</eventName>
		</eventNames>
	</passThru>
	<fileTargets>
		<fileTarget>
			<enableLogging>true</enableLogging>
			<fileName>AdtranAlarms.log</fileName>
			<eventNames>
				<eventName>50001*</eventName>
			</eventNames>
		</fileTarget>
		<fileTarget>
			<enableLogging>true</enableLogging>
			<fileName>CienaAlarms.log</fileName>
			<eventNames>
				<eventName>50002*</eventName>
			</eventNames>
		</fileTarget>
	</fileTargets>
	<cascadeTargets>
		<cascadeTarget name="SAREA_PD">
			<enableCascading>true</enableCascading>
			<vpName>SareaPdvp</vpName>
			<scenarioName>com.hp.uca.expert.vp.pd.ProblemDetection</scenarioName>
			<version>1.0</version>
			<eventNames>
				<eventName>50007/100/7</eventName>
				<eventName>50007/100/10</eventName>
			</eventNames>
		</cascadeTarget>
	</cascadeTargets>
	<healthTraps>
		<eventNames>
			<eventName>50002/100/55</eventName>
			<eventName>50002/100/14</eventName>
			<eventName>50002/100/21</eventName>
			<eventName>50002/100/19</eventName>
			<eventName>50002/100/52</eventName>
		</eventNames>
	</healthTraps>
</PreProcessPolicies>
